### ISSUE TITLE
运行的时候报错，要pod，需要吗？

### ISSUE THREAD

**Issue by feng-tianyou** [duowan/issue-13-VIPER-Objection#1]

**Comment by PonyCui** [comment]
pod install.

**Comment by feng-tianyou** [comment]
多问一句，这个VIPER框架你觉得怎样？我只是看懂一点，把Controller瘦身，逻辑放到外部处理，指教一下。有没有Objection的文章解释一下，最近想学习一下依赖注入。谢谢

**Comment by PonyCui** [comment]
VIPER 强大的地方在于，你可以将一个应用中的不同角色进行很好的区分。
ViewController 的瘦身是其第一步，更重要的是 VIPER 可以帮助你建立整个应用的骨架，拥有良好的骨架方可在其上建造更强大的应用。

**Comment by feng-tianyou** [comment]
嗯，我也是这样想的，但是框架区分太细，逻辑有点绕，新人很难上手（我就是=_=），会不会因为区分模块太细而造成代码混乱或者包和文件超级多？

**Comment by PonyCui** [comment]
不要害怕类和文件多。

**Comment by feng-tianyou** [comment]
好，谢谢你的回答
